<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Cart.aspx.vb" Inherits="Cart" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <br />
        <br />
        <asp:Label ID="lblCat" runat="server" Text="Choose a Category" style="font-weight: 700"></asp:Label>
        <!-- A label is created to outline different categories on the webpage. -->
        <br />
        <br />
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True">
            <asp:ListItem Value="0">--Select--</asp:ListItem>
            <asp:ListItem Value="1">Books</asp:ListItem>
            <asp:ListItem Value="2">Movies</asp:ListItem>
        </asp:DropDownList>
        <!-- A dropdown list is implemented to display 2 categories as well as an option that prompts the user to select one -->
        <br />
        <br />
        <asp:Label ID="lblProd" runat="server" Text="Available Products" style="font-weight: 700" Visible="False"></asp:Label>
        <!-- Label to display a list of available products -->
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateSelectButton="True" DataKeyNames="Pub_ID">
        </asp:GridView>
        <!-- A gridview that displays all books in the database and their properties-->
        <br />
        <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True">
        </asp:GridView>
        <!-- A gridview that displays all movies in the database and their properties -->
        <br />
        <asp:Label ID="lblTotal" runat="server" Text="Label" Visible="False" style="font-weight: 700"></asp:Label>
        <!-- A label that becomes visible when a product is selected -->
&nbsp;&nbsp;&nbsp;
        <asp:Label ID="lblAmount" runat="server" Text="Label" Visible="False"></asp:Label>
        <!-- A label that becomes visible when another product is selected -->
        <br />
        <br />
        <br />
        <asp:Button ID="btnCheckOut" runat="server" Text="Check Out" Visible="False" />
        <!-- A button that a user can press to submit the choice they have made -->
        <br />
        <br />
        <br />
    </div>
       
    </form>
</body>
</html>
